server:
  port: 8761

spring:
  application:
    name: eureka
  security:
    user:
      name: user
      password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
